### ISSUE TITLE
cool project!

### ISSUE THREAD

**Issue by aquynh** [chen-charles/PEDetour#1]
this looks like a cool project, but will you have a longer, with more details, README?

keep it up, cheers.

**Comment by chen-charles** [comment]
Thanks! I will update README soon :) You can try the release binaries for now, it has how-to included.

**Comment by aquynh** [comment]
great, we linked to your project now from http://www.capstone-engine.org/showcase.html & http://www.keystone-engine.org/showcase/

cheers.

**Comment by chen-charles** [comment]
Thanks!

cheers.
